name: test

on:
  push:
    paths-ignore:
      - '**.md'
    pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make postgres
        env:
          DOCKER_COMPOSE_ARGS: -d
      - run: make test
